#spring.datasource.url=jdbc:mysql://localhost:3306/ems?useSSL=false
spring.datasource.url=jdbc:mysql://mydb-instance.c10c280o6i1v.ap-south-1.rds.amazonaws.com:3306/ems?useSSL=false&serverTimezone=UTC
spring.datasource.username=admin3475
spring.datasource.password=ytury87589hjgyeao8

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update
